export async function GET() {
  return new Response(`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Recover POGs · Planogram Studio</title>
<style>body{font:16px/1.5 system-ui,sans-serif;margin:0;background:#f3f6f8;color:#182b36}main{max-width:960px;margin:32px auto;padding:24px}h1{font-size:28px}a{color:#075e65}button,.download{display:inline-block;background:#075e65;color:white;border:0;border-radius:8px;padding:12px 16px;font:inherit;cursor:pointer;text-decoration:none;margin:4px 8px 4px 0}button:disabled{opacity:.5;cursor:wait}.card{background:white;border:1px solid #ccd9df;border-radius:12px;padding:20px;margin:16px 0}small{display:block;color:#50616b;font-size:14px}.links a{display:inline-block;margin:10px 18px 0 0}#status{min-height:24px}h2{font-size:20px;margin:0 0 8px}select{font:inherit;padding:12px;border-radius:6px;max-width:100%}</style></head><body><main>
<a href="/">Planogram Studio</a><h1>Recover POGs and image library</h1>
<p>Read saved copies without opening the editor. Downloads do not replace or delete your workspace.</p>
<div class="card"><label for="source">Saved copy</label><br><select id="source"><option value="current">My current workspace</option><option value="legacy">Older master workspace (owner only)</option></select><p><button id="inspect">Find saved POGs</button><a class="download" id="backup" href="/api/recovery?download=workspace">Download full saved copy</a></p><small>The full copy includes embedded images and saved image links. Images stored separately remain linked; this is not a standalone archive of those image files.</small></div>
<p id="status" role="status" aria-live="polite">Choose “Find saved POGs” to inspect this copy.</p><div id="plans"></div>
<script>
const source=document.getElementById('source'),status=document.getElementById('status'),list=document.getElementById('plans'),button=document.getElementById('inspect'),backup=document.getElementById('backup');
source.onchange=()=>{backup.href='/api/recovery?download=workspace&source='+source.value;list.replaceChildren();status.textContent='Choose “Find saved POGs” to inspect this copy.'};
button.onclick=async()=>{button.disabled=true;source.disabled=true;list.replaceChildren();status.textContent='Reading saved POG names without loading their images. Large copies may take a moment…';
try{const response=await fetch('/api/recovery?source='+source.value,{cache:'no-store'});if(!response.ok){let message='Unable to read this copy. Try downloading the full saved copy.';try{message=(await response.json()).error||message}catch{}throw new Error(message)}const data=await response.json();
status.textContent=data.plans.length+' POGs found in the copy saved '+new Date(data.revision).toLocaleString()+'.';
for(const plan of data.plans){const card=document.createElement('article');card.className='card';const title=document.createElement('h2');title.textContent=plan.title;const detail=document.createElement('small');detail.textContent=plan.productCount+' products · '+plan.imageCount+' saved image entries';const links=document.createElement('div');links.className='links';for(const [kind,label] of [['pog','Download POG'],['library','Download image library records']]){const link=document.createElement('a');link.textContent=label;link.href='/api/recovery?source='+source.value+'&download='+kind+'&index='+plan.index+'&revision='+data.revision;links.append(link)}card.append(title,detail,links);list.append(card)}
if(!data.plans.length)status.textContent+=' Check the older master copy before making changes in the editor.';
}catch(error){status.textContent=error.message}finally{button.disabled=false;source.disabled=false}};
</script></main></body></html>`, { headers: { "content-type": "text/html; charset=utf-8", "cache-control": "no-store", "x-content-type-options": "nosniff" } });
}
